#!/bin/bash

#SBATCH --mem-per-cpu=10gb #Reserving memory
#SBATCH --job-name=ileAssemble # Job name
#SBATCH --partition=hugemem # Partition
#SBATCH --cpus-per-task=60 # Run on one node
#SBATCH --output=ILEUM_AssemblePairs.log # Standard output and error log
#SBATCH --mail-type=BEGIN,END,FAIL #Send e-mails
#SBATCH --mail-user=cmonzo@age.mpg.de

module load blast+
source /beegfs/group_lp/home/CMonzo/.bashrc
conda activate MPI_cmc

AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19250_I7_S7_001_PRIMER-S3_R1_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19250_I7_S7_001_PRIMER-S3_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19251_I8_S8_001_PRIMER-S4_R1_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19251_I8_S8_001_PRIMER-S4_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19252_I9_S9_001_PRIMER-S2_R1_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19252_I9_S9_001_PRIMER-S2_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19253_I10_S10_001_PRIMER-S10_R1_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19253_I10_S10_001_PRIMER-S10_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19249_I6_S6_001_PRIMER-S1_R1_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19249_I6_S6_001_PRIMER-S1_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19253_I10_S10_001_PRIMER-S2_R1_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19253_I10_S10_001_PRIMER-S2_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19249_I6_S6_001_PRIMER-S10_R1_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19249_I6_S6_001_PRIMER-S10_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19251_I8_S8_001_PRIMER-S7_R1_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19251_I8_S8_001_PRIMER-S7_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19251_I8_S8_001_PRIMER-S1_R1_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19251_I8_S8_001_PRIMER-S1_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19251_I8_S8_001_PRIMER-S9_R1_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19251_I8_S8_001_PRIMER-S9_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19250_I7_S7_001_PRIMER-S9_R1_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19250_I7_S7_001_PRIMER-S9_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19251_I8_S8_001_PRIMER-S3_R1_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19251_I8_S8_001_PRIMER-S3_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19250_I7_S7_001_PRIMER-S2_R1_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19250_I7_S7_001_PRIMER-S2_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19253_I10_S10_001_PRIMER-S8_R1_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19253_I10_S10_001_PRIMER-S8_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19252_I9_S9_001_PRIMER-S10_R1_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19252_I9_S9_001_PRIMER-S10_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19251_I8_S8_001_PRIMER-S6_R1_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19251_I8_S8_001_PRIMER-S6_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19251_I8_S8_001_PRIMER-S2_R1_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19251_I8_S8_001_PRIMER-S2_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19249_I6_S6_001_PRIMER-S8_R1_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19249_I6_S6_001_PRIMER-S8_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19252_I9_S9_001_PRIMER-S7_R1_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19252_I9_S9_001_PRIMER-S7_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19253_I10_S10_001_PRIMER-S6_R1_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19253_I10_S10_001_PRIMER-S6_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19253_I10_S10_001_PRIMER-S1_R1_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19253_I10_S10_001_PRIMER-S1_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19249_I6_S6_001_PRIMER-S4_R1_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19249_I6_S6_001_PRIMER-S4_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19249_I6_S6_001_PRIMER-S9_R1_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19249_I6_S6_001_PRIMER-S9_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19253_I10_S10_001_PRIMER-S5_R1_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19253_I10_S10_001_PRIMER-S5_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19250_I7_S7_001_PRIMER-S10_R1_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19250_I7_S7_001_PRIMER-S10_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19252_I9_S9_001_PRIMER-S6_R1_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19252_I9_S9_001_PRIMER-S6_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19249_I6_S6_001_PRIMER-S2_R1_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19249_I6_S6_001_PRIMER-S2_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19252_I9_S9_001_PRIMER-S5_R1_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19252_I9_S9_001_PRIMER-S5_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19252_I9_S9_001_PRIMER-S8_R1_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19252_I9_S9_001_PRIMER-S8_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19251_I8_S8_001_PRIMER-S5_R1_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19251_I8_S8_001_PRIMER-S5_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19253_I10_S10_001_PRIMER-S7_R1_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19253_I10_S10_001_PRIMER-S7_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19250_I7_S7_001_PRIMER-S1_R1_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19250_I7_S7_001_PRIMER-S1_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19250_I7_S7_001_PRIMER-S8_R1_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19250_I7_S7_001_PRIMER-S8_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19249_I6_S6_001_PRIMER-S3_R1_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19249_I6_S6_001_PRIMER-S3_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19249_I6_S6_001_PRIMER-S7_R1_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19249_I6_S6_001_PRIMER-S7_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19250_I7_S7_001_PRIMER-S4_R1_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19250_I7_S7_001_PRIMER-S4_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19250_I7_S7_001_PRIMER-S5_R1_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19250_I7_S7_001_PRIMER-S5_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19252_I9_S9_001_PRIMER-S4_R1_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19252_I9_S9_001_PRIMER-S4_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19252_I9_S9_001_PRIMER-S3_R1_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19252_I9_S9_001_PRIMER-S3_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19250_I7_S7_001_PRIMER-S7_R1_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19250_I7_S7_001_PRIMER-S7_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19252_I9_S9_001_PRIMER-S1_R1_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19252_I9_S9_001_PRIMER-S1_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19253_I10_S10_001_PRIMER-S4_R1_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19253_I10_S10_001_PRIMER-S4_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19249_I6_S6_001_PRIMER-S5_R1_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19249_I6_S6_001_PRIMER-S5_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19251_I8_S8_001_PRIMER-S10_R1_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19251_I8_S8_001_PRIMER-S10_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19253_I10_S10_001_PRIMER-S3_R1_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19253_I10_S10_001_PRIMER-S3_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19249_I6_S6_001_PRIMER-S6_R1_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19249_I6_S6_001_PRIMER-S6_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19251_I8_S8_001_PRIMER-S8_R1_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19251_I8_S8_001_PRIMER-S8_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19252_I9_S9_001_PRIMER-S9_R1_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19252_I9_S9_001_PRIMER-S9_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19253_I10_S10_001_PRIMER-S9_R1_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19253_I10_S10_001_PRIMER-S9_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19250_I7_S7_001_PRIMER-S6_R1_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19250_I7_S7_001_PRIMER-S6_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
