#!/bin/bash

#SBATCH --mem-per-cpu=10gb #Reserving memory
#SBATCH --job-name=ileIsotype # Job name
#SBATCH --partition=hugemem,himem # Partition
#SBATCH --cpus-per-task=60 # Run on one node
#SBATCH --output=ILEUM_AddIsotype.log # Standard output and error log
#SBATCH --mail-type=BEGIN,END,FAIL #Send e-mails
#SBATCH --mail-user=cmonzo@age.mpg.de

module load blast+
source /beegfs/group_lp/home/CMonzo/.bashrc
conda activate MPI_cmc


MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19251_I8_S8_001_PRIMER-S6_R1_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19249_I6_S6_001_PRIMER-S1_R1_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19250_I7_S7_001_PRIMER-S10_R1_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19253_I10_S10_001_PRIMER-S5_R1_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19253_I10_S10_001_PRIMER-S3_R1_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19252_I9_S9_001_PRIMER-S10_R1_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19250_I7_S7_001_PRIMER-S5_R1_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19249_I6_S6_001_PRIMER-S7_R1_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19249_I6_S6_001_PRIMER-S2_R1_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19249_I6_S6_001_PRIMER-S9_R1_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19252_I9_S9_001_PRIMER-S7_R1_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19253_I10_S10_001_PRIMER-S4_R1_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19251_I8_S8_001_PRIMER-S3_R1_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19250_I7_S7_001_PRIMER-S6_R1_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19253_I10_S10_001_PRIMER-S1_R1_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19252_I9_S9_001_PRIMER-S3_R1_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19253_I10_S10_001_PRIMER-S8_R1_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19249_I6_S6_001_PRIMER-S5_R1_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19252_I9_S9_001_PRIMER-S2_R1_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19250_I7_S7_001_PRIMER-S8_R1_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19253_I10_S10_001_PRIMER-S10_R1_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19251_I8_S8_001_PRIMER-S5_R1_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19252_I9_S9_001_PRIMER-S4_R1_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19250_I7_S7_001_PRIMER-S1_R1_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19250_I7_S7_001_PRIMER-S4_R1_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19252_I9_S9_001_PRIMER-S6_R1_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19251_I8_S8_001_PRIMER-S9_R1_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19253_I10_S10_001_PRIMER-S6_R1_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19251_I8_S8_001_PRIMER-S1_R1_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19251_I8_S8_001_PRIMER-S8_R1_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19252_I9_S9_001_PRIMER-S9_R1_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19251_I8_S8_001_PRIMER-S10_R1_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19250_I7_S7_001_PRIMER-S2_R1_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19252_I9_S9_001_PRIMER-S1_R1_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19250_I7_S7_001_PRIMER-S7_R1_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19249_I6_S6_001_PRIMER-S3_R1_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19253_I10_S10_001_PRIMER-S7_R1_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19250_I7_S7_001_PRIMER-S3_R1_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19251_I8_S8_001_PRIMER-S4_R1_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19252_I9_S9_001_PRIMER-S8_R1_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19249_I6_S6_001_PRIMER-S10_R1_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19249_I6_S6_001_PRIMER-S8_R1_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19251_I8_S8_001_PRIMER-S2_R1_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19253_I10_S10_001_PRIMER-S9_R1_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19253_I10_S10_001_PRIMER-S2_R1_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19249_I6_S6_001_PRIMER-S4_R1_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19251_I8_S8_001_PRIMER-S7_R1_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19250_I7_S7_001_PRIMER-S9_R1_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19252_I9_S9_001_PRIMER-S5_R1_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19249_I6_S6_001_PRIMER-S6_R1_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
