#!/bin/bash

#SBATCH --mem-per-cpu=10gb #Reserving memory
#SBATCH --job-name=SPLAssemble # Job name
#SBATCH --partition=hugemem # Partition
#SBATCH --cpus-per-task=60 # Run on one node
#SBATCH --output=./logs/SPL_AssemblePairs.log # Standard output and error log
#SBATCH --mail-type=BEGIN,END,FAIL #Send e-mails
#SBATCH --mail-user=cmonzo@age.mpg.de

module load blast+
source /beegfs/group_lp/home/CMonzo/.bashrc
source ~/myconda.sh

AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19248_S5_S5_001_PRIMER-S7_R1_pair-pass_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19248_S5_S5_001_PRIMER-S7_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19246_S3_S3_001_PRIMER-S2_R1_pair-pass_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19246_S3_S3_001_PRIMER-S2_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19248_S5_S5_001_PRIMER-S6_R1_pair-pass_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19248_S5_S5_001_PRIMER-S6_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19248_S5_S5_001_PRIMER-S3_R1_pair-pass_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19248_S5_S5_001_PRIMER-S3_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19248_S5_S5_001_PRIMER-S1_R1_pair-pass_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19248_S5_S5_001_PRIMER-S1_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19245_S2_S2_001_PRIMER-S9_R1_pair-pass_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19245_S2_S2_001_PRIMER-S9_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19246_S3_S3_001_PRIMER-S7_R1_pair-pass_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19246_S3_S3_001_PRIMER-S7_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19247_S4_S4_001_PRIMER-S8_R1_pair-pass_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19247_S4_S4_001_PRIMER-S8_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19245_S2_S2_001_PRIMER-S3_R1_pair-pass_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19245_S2_S2_001_PRIMER-S3_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19245_S2_S2_001_PRIMER-S1_R1_pair-pass_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19245_S2_S2_001_PRIMER-S1_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19245_S2_S2_001_PRIMER-S5_R1_pair-pass_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19245_S2_S2_001_PRIMER-S5_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19244_S1_S1_001_PRIMER-S4_R1_pair-pass_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19244_S1_S1_001_PRIMER-S4_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19245_S2_S2_001_PRIMER-S7_R1_pair-pass_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19245_S2_S2_001_PRIMER-S7_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19244_S1_S1_001_PRIMER-S2_R1_pair-pass_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19244_S1_S1_001_PRIMER-S2_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19244_S1_S1_001_PRIMER-S10_R1_pair-pass_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19244_S1_S1_001_PRIMER-S10_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19245_S2_S2_001_PRIMER-S2_R1_pair-pass_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19245_S2_S2_001_PRIMER-S2_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19245_S2_S2_001_PRIMER-S10_R1_pair-pass_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19245_S2_S2_001_PRIMER-S10_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19246_S3_S3_001_PRIMER-S8_R1_pair-pass_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19246_S3_S3_001_PRIMER-S8_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19247_S4_S4_001_PRIMER-S10_R1_pair-pass_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19247_S4_S4_001_PRIMER-S10_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19248_S5_S5_001_PRIMER-S8_R1_pair-pass_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19248_S5_S5_001_PRIMER-S8_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19244_S1_S1_001_PRIMER-S1_R1_pair-pass_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19244_S1_S1_001_PRIMER-S1_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19248_S5_S5_001_PRIMER-S4_R1_pair-pass_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19248_S5_S5_001_PRIMER-S4_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19247_S4_S4_001_PRIMER-S2_R1_pair-pass_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19247_S4_S4_001_PRIMER-S2_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19245_S2_S2_001_PRIMER-S6_R1_pair-pass_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19245_S2_S2_001_PRIMER-S6_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19245_S2_S2_001_PRIMER-S4_R1_pair-pass_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19245_S2_S2_001_PRIMER-S4_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19247_S4_S4_001_PRIMER-S9_R1_pair-pass_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19247_S4_S4_001_PRIMER-S9_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19248_S5_S5_001_PRIMER-S10_R1_pair-pass_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19248_S5_S5_001_PRIMER-S10_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19246_S3_S3_001_PRIMER-S1_R1_pair-pass_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19246_S3_S3_001_PRIMER-S1_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19244_S1_S1_001_PRIMER-S8_R1_pair-pass_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19244_S1_S1_001_PRIMER-S8_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19246_S3_S3_001_PRIMER-S6_R1_pair-pass_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19246_S3_S3_001_PRIMER-S6_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19246_S3_S3_001_PRIMER-S4_R1_pair-pass_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19246_S3_S3_001_PRIMER-S4_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19247_S4_S4_001_PRIMER-S5_R1_pair-pass_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19247_S4_S4_001_PRIMER-S5_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19248_S5_S5_001_PRIMER-S2_R1_pair-pass_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19248_S5_S5_001_PRIMER-S2_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19244_S1_S1_001_PRIMER-S3_R1_pair-pass_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19244_S1_S1_001_PRIMER-S3_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19244_S1_S1_001_PRIMER-S5_R1_pair-pass_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19244_S1_S1_001_PRIMER-S5_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19247_S4_S4_001_PRIMER-S6_R1_pair-pass_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19247_S4_S4_001_PRIMER-S6_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19246_S3_S3_001_PRIMER-S10_R1_pair-pass_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19246_S3_S3_001_PRIMER-S10_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19245_S2_S2_001_PRIMER-S8_R1_pair-pass_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19245_S2_S2_001_PRIMER-S8_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19246_S3_S3_001_PRIMER-S9_R1_pair-pass_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19246_S3_S3_001_PRIMER-S9_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19246_S3_S3_001_PRIMER-S3_R1_pair-pass_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19246_S3_S3_001_PRIMER-S3_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19248_S5_S5_001_PRIMER-S9_R1_pair-pass_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19248_S5_S5_001_PRIMER-S9_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19247_S4_S4_001_PRIMER-S4_R1_pair-pass_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19247_S4_S4_001_PRIMER-S4_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19246_S3_S3_001_PRIMER-S5_R1_pair-pass_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19246_S3_S3_001_PRIMER-S5_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19244_S1_S1_001_PRIMER-S7_R1_pair-pass_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19244_S1_S1_001_PRIMER-S7_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19244_S1_S1_001_PRIMER-S9_R1_pair-pass_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19244_S1_S1_001_PRIMER-S9_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19247_S4_S4_001_PRIMER-S1_R1_pair-pass_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19247_S4_S4_001_PRIMER-S1_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19248_S5_S5_001_PRIMER-S5_R1_pair-pass_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19248_S5_S5_001_PRIMER-S5_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19244_S1_S1_001_PRIMER-S6_R1_pair-pass_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19244_S1_S1_001_PRIMER-S6_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19247_S4_S4_001_PRIMER-S3_R1_pair-pass_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19247_S4_S4_001_PRIMER-S3_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
AssemblePairs.py sequential -1 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19247_S4_S4_001_PRIMER-S7_R1_pair-pass_consensus-pass_pair-pass.fastq -2 ../../data/fastq_UMI/build_consensus/dedup-mpg_L19247_S4_S4_001_PRIMER-S7_R2_pair-pass_consensus-pass_pair-pass.fastq -r ../../metadata/databases/igblast/fasta/imgt_mouse_ig_v.fasta --coord presto --rc tail --scanrev --aligner blastn --outdir ../../data/fastq_assembled/consensus/ --1f PRIMER CONSCOUNT --2f CONSCOUNT --nproc 60
