#!/bin/bash

#SBATCH --mem-per-cpu=10gb #Reserving memory
#SBATCH --job-name=splIsotype # Job name
#SBATCH --partition=hugemem,himem # Partition
#SBATCH --cpus-per-task=60 # Run on one node
#SBATCH --output=./logs/SPL_AddIsotype.log # Standard output and error log
#SBATCH --mail-type=BEGIN,END,FAIL #Send e-mails
#SBATCH --mail-user=cmonzo@age.mpg.de

module load blast+
source /beegfs/group_lp/home/CMonzo/.bashrc
conda activate MPI_cmc


MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19245_S2_S2_001_PRIMER-S3_R1_pair-pass_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19247_S4_S4_001_PRIMER-S6_R1_pair-pass_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19244_S1_S1_001_PRIMER-S9_R1_pair-pass_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19246_S3_S3_001_PRIMER-S4_R1_pair-pass_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19247_S4_S4_001_PRIMER-S4_R1_pair-pass_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19246_S3_S3_001_PRIMER-S8_R1_pair-pass_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19245_S2_S2_001_PRIMER-S4_R1_pair-pass_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19244_S1_S1_001_PRIMER-S2_R1_pair-pass_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19245_S2_S2_001_PRIMER-S7_R1_pair-pass_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19246_S3_S3_001_PRIMER-S10_R1_pair-pass_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19244_S1_S1_001_PRIMER-S1_R1_pair-pass_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19248_S5_S5_001_PRIMER-S8_R1_pair-pass_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19246_S3_S3_001_PRIMER-S7_R1_pair-pass_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19244_S1_S1_001_PRIMER-S5_R1_pair-pass_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19247_S4_S4_001_PRIMER-S2_R1_pair-pass_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19247_S4_S4_001_PRIMER-S3_R1_pair-pass_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19248_S5_S5_001_PRIMER-S3_R1_pair-pass_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19246_S3_S3_001_PRIMER-S3_R1_pair-pass_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19247_S4_S4_001_PRIMER-S9_R1_pair-pass_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19247_S4_S4_001_PRIMER-S7_R1_pair-pass_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19248_S5_S5_001_PRIMER-S5_R1_pair-pass_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19248_S5_S5_001_PRIMER-S4_R1_pair-pass_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19244_S1_S1_001_PRIMER-S4_R1_pair-pass_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19248_S5_S5_001_PRIMER-S7_R1_pair-pass_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19247_S4_S4_001_PRIMER-S8_R1_pair-pass_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19245_S2_S2_001_PRIMER-S6_R1_pair-pass_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19245_S2_S2_001_PRIMER-S8_R1_pair-pass_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19245_S2_S2_001_PRIMER-S2_R1_pair-pass_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19246_S3_S3_001_PRIMER-S1_R1_pair-pass_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19248_S5_S5_001_PRIMER-S6_R1_pair-pass_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19247_S4_S4_001_PRIMER-S1_R1_pair-pass_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19245_S2_S2_001_PRIMER-S1_R1_pair-pass_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19248_S5_S5_001_PRIMER-S9_R1_pair-pass_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19244_S1_S1_001_PRIMER-S6_R1_pair-pass_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19246_S3_S3_001_PRIMER-S5_R1_pair-pass_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19244_S1_S1_001_PRIMER-S7_R1_pair-pass_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19248_S5_S5_001_PRIMER-S10_R1_pair-pass_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19248_S5_S5_001_PRIMER-S1_R1_pair-pass_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19245_S2_S2_001_PRIMER-S10_R1_pair-pass_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19247_S4_S4_001_PRIMER-S10_R1_pair-pass_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19246_S3_S3_001_PRIMER-S9_R1_pair-pass_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19246_S3_S3_001_PRIMER-S6_R1_pair-pass_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19247_S4_S4_001_PRIMER-S5_R1_pair-pass_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19246_S3_S3_001_PRIMER-S2_R1_pair-pass_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19248_S5_S5_001_PRIMER-S2_R1_pair-pass_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19245_S2_S2_001_PRIMER-S9_R1_pair-pass_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19244_S1_S1_001_PRIMER-S10_R1_pair-pass_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19244_S1_S1_001_PRIMER-S3_R1_pair-pass_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19245_S2_S2_001_PRIMER-S5_R1_pair-pass_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
MaskPrimers.py align -s ../../data/fastq_assembled/consensus/dedup-mpg_L19244_S1_S1_001_PRIMER-S8_R1_pair-pass_consensus-pass_pair-pass_assemble-pass.fastq -p ../../metadata/presto_PCR1_ISOTYPES.fasta --maxlen 110 --maxerror 0.3 --failed --nproc 60 --revpr --mode tag --pf ISOTYPE --outdir ../../data/fastq_assembled/isotype/
